### ISSUE TITLE
Add chapter number to code/table/figure numbering

### ISSUE THREAD

**Issue by Davideko212** [HTL3R-DA-24-25/da-vorlage#18] opened 2024-12-24 00:01 UTC
The current implementation treats the numbering in all chapters the same and counts from 1 to n over the entire document.

This can get confusing quite quickly and it doesn't follow the school guidelines for numbering figures, tables and code snippets. 

Correct Example:
![image](https://github.com/user-attachments/assets/4a203262-235e-443a-9c7c-9e5d498b9590)

**Comment by cauvmou** [comment] 2024-12-24 01:04
Duplicate of #16

**Closed by cauvmou** 2024-12-24 01:04 UTC
